print("This is an example for a test")
print("This is a second line.....")
print("This is a third line.....")
print("This is a fourth line.....")
print("This is a fifth line.....")
print("This is a sixth line.....")
print("This is a seventh line.....")
print("This is a eighth line.....")